# Project information
site_name: jDuck
site_url: https://luu.github.io/jduck/
site_author: TP-Luu
site_description: >-
  An open-source robot platform for learning robotics and AI with NVIDIA Jeston Nano board.

# Repository
repo_name: luutp/jduck
repo_url: https://github.com/luutp/jduck
edit_uri: blob/master/docs

# Copyright
copyright: Copyright &copy; 2021 Trieu Phat Luu

# Configuration
theme:
    name: "material"    
    logo: images/jduck_logo.png
    favicon: images/favicon.png
    font: Incosolata
    palette:      
      primary: orange
      accent: blue
    features:
      - navigation.expand

# Plugin
plugins:
  - search
  - minify:
      minify_html: true
use_directory_urls: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luutp
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/trieuphatluu/
  generator: false
extra_css:
  - css/colors.css

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started: getting_started.md  
  - Bill of Materials: BOM.md  
  - Hardware Setup: hardware_setup.md
  - Software Setup:
      - Jetson Nano Setup: software_setup/jetson_nano_setup.md      
      - JDuck Setup: software_setup/jduck_setup.md      
  - Examples: 
      - Basic Motion: examples/basic_motion.md
      - Teleoperation: examples/teleoperation.md
      - Collision Avoidance: examples/collision_avoidance.md
      - Road Following: examples/road_following.md
      - Object Following: examples/object_following.md
  - Reference:      
      - Contributing: CONTRIBUTING.md
      - Changes: CHANGELOG.md      
