name: CI

on:
  # Trigger the workflow on push or pull request, for develop branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


jobs:
  # Run linter with github actions for quick feedbacks.
  linter:
    runs-on: ubuntu-latest
    # run on PRs, or commits to facebookresearch (not internal)    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8==3.8.1 flake8-bugbear flake8-comprehensions isort==4.3.21
          python -m pip install black==20.8b1
          flake8 --version
      - name: Lint
        run: |
          echo "Running isort"
          isort -c -sp .
          echo "Running black"
          black -l 100 --check .
          echo "Running flake8"
          flake8 .
